[package]
name = "diff-explore"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.25"
chrono = "0.4.23"
tui = "0.19"
once_cell = "1.16.0"
notify = "5.0.0"
regex = "1.7.0"

[[bin]]
name = "de"
path = "src/main.rs"
