[package]
name = "list_helper_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
list_helper_core = { path = "../core" }

[lib]
proc-macro = true
