[package]
name = "list_helper_macro"
version.workspace = true
edition.workspace = true

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
list_helper_core = { path = "../core" }

[lib]
proc-macro = true
